--- src/Makefile.orig	2024-08-17 16:34:43.525322400 +0200
+++ src/Makefile	2024-08-19 00:34:24.523942434 +0200
@@ -30,17 +30,17 @@
 #DEL   = del
 ##### Unix definitions
 SHELL = /bin/sh
-CC    = cc -I. -O
+#CC    = gcc -I.
+#CXXFLAGS = -g2
 CLEAN = strip a.out ; rm *.o ; mv a.out $@
-SLIB  = -lm
+#SLIB  = -lm
 COPY  = cp -p
 DEL   = rm -f
 #########################################
 
 ##### Files:
-UTIL  = prtgsc.c dispos.c decode_c.c get_head.c find_reg.c \
-	to_d.c dtos.c
-PGMS  = gsc.exe decode.exe
+UTIL  = prtgsc.c dispos.c decode_c.c get_head.c find_reg.c to_d.c dtos.c
+PGMS  = gsc decode
 PLATEPOCHS = ../plates.epoch
 
 # Directories by Declination
@@ -50,27 +50,27 @@
 
 # DEPENDENCIES	--------------------------------
 
-default: gsc.exe decode.exe
+default: gsc decode
 
 ### Query Program:
-gsc.exe: gsc.c $(UTIL) gsc.h
-	$(CC) gsc.c $(UTIL) $(SLIB)
-	$(CLEAN)
+gsc: gsc.c $(UTIL) gsc.h
+	$(CC) -I. $(CXXFLAGS) gsc.c $(UTIL) -o ../bin/$@ -lm $(LDFLAGS)
+	# $(CLEAN)
 
 ### Edit a full file to stdout:
-decode.exe: decode.c decode_c.c get_head.c prtgsc.c dtos.c gsc.h
-	$(CC) decode.c decode_c.c get_head.c prtgsc.c dtos.c $(SLIB)
-	$(CLEAN)
+decode: decode.c decode_c.c get_head.c prtgsc.c dtos.c gsc.h
+	$(CC) -I. $(CXXFLAGS) decode.c decode_c.c get_head.c prtgsc.c dtos.c -o ../bin/$@ -lm $(LDFLAGS)
+	# $(CLEAN)
 
 ### Generate the Index of Regions:
-genreg.exe: genreg.c  get_head.c find_reg.c gsc.h
-	$(CC) genreg.c get_head.c find_reg.c
-	$(CLEAN)
+genreg: genreg.c get_head.c find_reg.c gsc.h
+	$(CC) -I. $(CXXFLAGS) genreg.c get_head.c find_reg.c -o $@ -lm $(LDFLAGS)
+	# $(CLEAN)
 
 ### Relation Plate --> Epoch
 epoch: epoch.c get_head.c gsc.h
-	$(CC) epoch.c get_head.c
-	$(CLEAN)
+	$(CC) -I. $(CXXFLAGS) epoch.c get_head.c -o $@ -lm $(LDFLAGS)
+	# $(CLEAN)
 
 ### Generate the Binary Files from FITS
 encode: encode.c
@@ -105,12 +105,11 @@
 	    cat ../$$d/=done= || exit 1 ; \
 	done
 
-install: $(PGMS) genreg.exe phase2
-	$(COPY) gsc.exe decode.exe ../bin
-	GSCDAT=`pwd`/..; export GSCDAT; genreg.exe -b -c -d
+install: $(PGMS) genreg phase2
+	GSCDAT=`pwd`/..; export GSCDAT; ./genreg -b -c -d
 
 clean:
-	$(DEL) *.exe epoch encode core
+	$(DEL) gsc decode genreg epoch encode core
 
 
 #############################################################################
